import path from 'node:path';
import {
  blue,
  geekblue,
  green,
  orange,
  presetDarkPalettes,
  presetPalettes,
  red,
} from '@ant-design/colors';
import fs from 'fs-extra';
import { line } from './util.js';

let colorTemplate = '// DONT EDIT AUTO GENERATED BY ANTD COLORS\n';
let lightStatusTemplate = '';
let darkStatusTemplate = '';
const colorVarsMap = {
  primary: {
    colors: blue,
    label: 'blue',
  },
  success: {
    colors: green,
    label: 'green',
  },
  danger: {
    colors: red,
    label: 'red',
  },
  warning: {
    colors: orange,
    label: 'orange',
  },
  link: {
    colors: geekblue,
    label: 'geekblue',
  },
};

function generateColorFile() {
  // light
  Object.keys(presetPalettes).forEach((key) => {
    const colors = presetPalettes[key];

    colors.forEach((color, idx) => {
      const ci = idx + 1;
      if (idx === 5) {
        colorTemplate += `@${key}-${ci}: ${color};\n`;
        return;
      }
      colorTemplate += `@${key}-${ci}: color-palette(@${key}-6, ${ci});\n`;
    });

    colorTemplate += '\n';
  });

  // dark
  Object.keys(presetDarkPalettes).forEach((key) => {
    const colors = presetDarkPalettes[key];

    colors.forEach((color, idx) => {
      const ci = idx + 1;
      colorTemplate += `@dark-${key}-${ci}: color-palette-dark(@${key}-6, ${ci});\n`;
    });
    colorTemplate += '\n';
  });

  fs.outputFile(path.resolve('./colors.less'), colorTemplate);
}

function generateLessStatusVars() {
  const colorsVarsArr = Object.keys(colorVarsMap);
  colorsVarsArr.forEach((key, vi) => {
    const { colors, label } = colorVarsMap[key];
    colors.forEach((color, idx) => {
      const ci = idx + 1;
      const canLine = line(vi, colorsVarsArr.length, idx, colors.length);
      lightStatusTemplate += `@${key}-${ci}: rgb(var(--${label}-${ci}));\n`;
      darkStatusTemplate += `@dark-${key}-${ci}: rgb(var(--${label}-${ci}));${canLine}`;
    });

    lightStatusTemplate += '\n';
    darkStatusTemplate += (vi === colorsVarsArr.length - 1) ? '' : '\n';
  });

  fs.outputFile(path.resolve('./colors.less'), `${colorTemplate}${lightStatusTemplate}${darkStatusTemplate}`);
}

export function generatorColors() {
  generateColorFile();
  generateLessStatusVars();
}
